apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: arghaya
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3a.large
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: t3a.large
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub
